name: Black Duck SCA

on:
  push:
    branches: [ master, main, develop, stage, release ]
  pull_request:
    branches: [ master, main, develop, stage, release ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  security-events: write

jobs:
  blackduck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Black Duck SCA Scan
        uses: blackduck-inc/black-duck-security-scan@v2

        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          DETECT_PROJECT_VERSION_NAME: sca-lab

        with:
          blackducksca_url: ${{ vars.BLACKDUCK_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCK_API_TOKEN }}

          blackducksca_scan_failure_severities: BLOCKER

          blackducksca_fixpr_enabled: true
          blackducksca_prComment_enabled: true

          blackducksca_reports_sarif_create: true
          blackducksca_upload_sarif_report: true

          github_token: ${{ secrets.GITHUB_TOKEN }}

          include_diagnostics: true

          detect_args: >-
            --detect.tools=DETECTOR,SIGNATURE_SCAN
            --detect.blackduck.signature.scanner.snippet.matching=SNIPPET_MATCHING
            --detect.accuracy.required=NONE
            --detect.detector.search.continue=true